repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4  # Use the latest stable version
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/mwouts/jupytext
    rev: v1.17.0
    hooks:
    - id: jupytext
      args: [--sync]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout