[project]
name = ""
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hydra-core>=1.3.5",
    "pre-commit",
]

[tool.ruff]
line-length = 125
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
# possible rules: https://beta.ruff.rs/docs/rules/
select = [
  "B",   # flake8-bugbear
  "C",   # flake8-comprehensions
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "W",   # pycodestyle warnings
  "PL",  # pylint
  "N",   # pep-8 variable names
  "S",   # flake8-bandit
  "RUF", # ruff rules
]

ignore = [
  "ANN002", # missing type annotation for *args
  "ANN003", # missing type annotation for **kwargs
  "ANN101", # missing type annotation for self in method
  "ANN102", # missing type annotation for cls in class methods
  "B027",   # abstract decorator for property but deprecated in ABC
  "D100",   # module docstrings
  "D104",   # package docstrings
  "D203",
  "D213",
  "D401",   # imperative mood for the first line
  "D407",   # dashed underline after Returns
  "E402",
  "E741",   # ambiguous variable name
  "N801",
  "N806",
  "N803",
  "N812",
  "N815",
  "N816",
  "PLW2901", 
  "PLR2004",
  "RUF013", # implicit optional -> should be removed when annotation is added
  "S113",    # requests wo timeout 
  "S101",   # use of assert
  "PLR0133" # constant check
]